### ISSUE TITLE
frontend not receiving content from rc-server

### ISSUE THREAD

**Issue by elroykanye** [transkript/reportcard-frontend#10]
To have this application running with all demo data available, the backend will be needed. This could just be bundled as a jar file and placed in the frontend to run before an `ng serve`.
This could tie with #6 after the backend has been setup to run auto with the frontend.

**Comment by elroykanye** [comment]
@mulfranck
I believe you share the same concerns as stated in this issue.

**Comment by mulfranck** [comment]
How can the backup data be bundled?

**Comment by elroykanye** [comment]
It's not been automated yet so it might be quite tedious at first.
Requires that you have JDK setup locally and the .jar file of the compiled backend.

After that, a post request is sent to the backend server to load some default data which can then be seen on the frontend.

**Comment by mulfranck** [comment]
What version of Java was used to compiled the ```rc.jar```? tried running it and had this error.
![running_rc_jar](https://user-images.githubusercontent.com/74215941/174248682-50be1626-3a5a-4e33-96e2-6daef8f028ce.png)

Was made to understand it was due to the version difference of the JRE and JDK.

**Comment by elroykanye** [comment]
Hm. Java 17 was used. Features such as records and switch returns are used in the backend that's why we have this requirement. Just do the necessary updates. We may have to include this in the readme, don't you think?

**Comment by mulfranck** [comment]
Exactly, I would see to adding that in readme if it is resolved.

**Comment by elroykanye** [comment]
> It's not been automated yet so it might be quite tedious at first.

At the time of this comment, there's a script available (`run`) which only downloads the latest jar bundle released and adds in the necessary path. 
Modifications may be made to this later so it functions better, but it can be a good fit for now.

**Comment by mulfranck** [comment]
I notice an infinite loop of GET request to /api/default/test

![image](https://user-images.githubusercontent.com/74215941/174430461-5e0dcea1-3ac9-4ed9-a27c-91b9bd602234.png)

![infinite_loop_of_request_at_api_default_test](https://user-images.githubusercontent.com/74215941/174430386-ddbd3e72-3a35-466f-92d5-6412bb43c892.png)

**Comment by elroykanye** [comment]
Oh! The backend was updated. I will update the jar file and let you know.

**Comment by mulfranck** [comment]
Okay, great.

**Comment by elroykanye** [comment]
Yea that's going to be a bit of pain right now 😄 the backend is not stable enough to automate releases

**Comment by elroykanye** [comment]
Hi @mulfranck , you can get the new release from the backend repo tagged `v0.0.2-alpha`

**Comment by elroykanye** [comment]
I think this issue has been resolved with including the backend jar in the run script for the frontend. That said, I will be closing this. Thanks for your help @mulfranck ! 😄

**Comment by mulfranck** [comment]
Thank you. Had great knowledge on OSS from this too. 🤝
