### ISSUE TITLE
students table not refrshing on action

### ISSUE THREAD

**Issue by Dezzy12** [transkript/reportcard-frontend#18]
Whenever an action is performed like adding,editing and deleting the student table does not refresh.  
I would expect that after performing each action, the students should automatically update 

![Screenshot from 2022-06-14 14-39-58](https://user-images.githubusercontent.com/98283956/173593500-b095d37c-2a80-4a60-b923-61776ae0d920.png)

![Screenshot from 2022-06-14 14-40-04](https://user-images.githubusercontent.com/98283956/173593525-26ee9d03-47b9-4810-bf56-41b21d4a9e50.png)

![Screenshot from 2022-06-14 14-40-08](https://user-images.githubusercontent.com/98283956/173593544-ed5021aa-6a81-4741-a79d-cb775a3092f5.png)

It shows successfully deleted but the student is still there
![Screenshot from 2022-06-14 14-40-31](https://user-images.githubusercontent.com/98283956/173593572-70ebf579-a82d-4428-b5e3-e614701e45a1.png)

**Comment by mulfranck** [comment]
I work like to work on this :)

**Comment by mulfranck** [comment]
I tried loading the added student in the background to no avail.
Though, when the modal is closed the table is refreshed, and all the added students are displayed.

If this can meet the requirement, then I will create the PR.

![load_on_close](https://user-images.githubusercontent.com/74215941/175326967-13046d6d-1d7c-4187-8882-a8c9cd54c39d.gif)

**Comment by elroykanye** [comment]
What method did you use to load?

**Comment by elroykanye** [comment]
Yes! That's it
