### ISSUE TITLE
Error message not making sense

### ISSUE THREAD

**Issue by Dezzy12** [transkript/reportcard-frontend#19]
Could not understand the error message after clicking on the Load Classes button
![Screenshot from 2022-06-14 14-55-41](https://user-images.githubusercontent.com/98283956/173595712-7bac1b03-38fa-496e-94c1-58a8fe92ea85.png)

**Comment by mulfranck** [comment]
Do you have the backend run? if not, the error might be related with #10. Just check it out.

**Comment by elroykanye** [comment]
@mulfranck , I think the issue here could be that the error message is not descriptive enough. A user won't have a clue what localhost means. This is indeed my fault of course, for displaying `err.message` instead of `err.error.message` in the error handler of most API subscriptions.

**Comment by elroykanye** [comment]
Please confirm with latest code on the master branch if this has been resolved :)
