### ISSUE TITLE
[BUG] Menu Not Scrollable 

### ISSUE THREAD

**Issue by mofirojean** [transkript/reportcard-frontend#23]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The settings cant be accessed cause the menu section is not scroll-able
![Screenshot from 2022-06-22 11-09-28](https://user-images.githubusercontent.com/93985482/175006017-ad8b86d3-be01-40c9-98fe-1390037c8fa9.png)

### Expected Behavior

menu was to be Scroll-able in order to access the other options

### Steps To Reproduce

go to the dashboard and you will find out that the setting items is not visible 

### Environment

```markdown
- OS: Ubuntu 20.04
- Node: v16.15.0
- npm: 8.5.5
```

**Comment by mulfranck** [comment]
Having a scrollbar for the menu is not commonly seen but can be a solution to this issue.
Have the scrollbar appear just for shorter or reduced screen height.

**Comment by elroykanye** [comment]
I am of an unpopular opinion to change the look of the menu itself. Currently, loading a page does not indicate on the item whose page is loaded.
This is another issue that could come up from this.
