### ISSUE TITLE
[BUG] Server error upon signup

### ISSUE THREAD

**Issue by de-lia** [transkript/reportcard-frontend#34]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After filling the required fields of the signup form and clicking sign in, a red box pops up which shows that an error has occurred instead of creating my account.

![Screenshot from 2022-08-01 13-52-37](https://user-images.githubusercontent.com/94251956/182158377-09a8f986-4969-40ca-899d-2caeeecdbb10.png)

### Expected Behavior

After prompting to sign up, the system should ask me to verify my email address and redirect me to my new dashboard if I have clicked the link that the system has provided. Or, any other 2-factor authentication methods could still be used.

### Steps To Reproduce

1. Make sure to fetch and pull the latest changes, On the terminal, type out <code>git pull</code> on the terminal to pull changes to the local repository after fetching the changes to the remote repository.
2. After pulling, type out <code>ng serve</code>.
3. Then add dashboard/home to the localhost:4200/ that you navigated to. 
4. On the Login form, click on 'Create today'.
5. Fill in all the fields and click on Sign in.

### Environment

```markdown
- OS:Ubuntu 20.04
- Node:13.14.0
- npm: 7.6.3
```

**Comment by elroykanye** [comment]
The existing backend run by the current frontend is an old version I have to manually replace when I merge incoming changes on the frontend. Will be updating today as you really need it.

**Comment by de-lia** [comment]
Thank you.😃

**Comment by elroykanye** [comment]
Get the backend server from [here ](https://github.com/transkript/reportcard-backend/releases/tag/v0.0.3)and replace in the `dist-app` directory.
