### ISSUE TITLE
Navbar elements and icon are not visible

### ISSUE THREAD

**Issue by mofirojean** [transkript/reportcard-frontend#38]
### Description

The navbar elements are not visible, a need to change its color to white   

Image of the issue can be seen bellow
![Screenshot from 2022-08-02 14-34-56](https://user-images.githubusercontent.com/93985482/182388538-50548bbe-2c67-4893-82e9-dcded96da402.png)

**Comment by elroykanye** [comment]
@moforemmanuel, do you think you can work on this?

**Comment by mofirojean** [comment]
Yeah its worth a try

**Comment by mofirojean** [comment]
@elroykanye  can i work on this?

**Comment by elroykanye** [comment]
Yes please.

**Comment by mofirojean** [comment]
i have located the file how do i go about it
