### ISSUE TITLE
change colour of cancel button on select-school component

### ISSUE THREAD

**Issue by mofirojean** [transkript/reportcard-frontend#40]
### Description

The color of the cancel button has to be red and not blue

Image of the issue is given bellow
![Screenshot from 2022-08-02 16-18-23](https://user-images.githubusercontent.com/93985482/182411033-e80cac00-3acb-4a58-bbde-319e48a6b3ea.png)

**Comment by tcyekov** [comment]
@elroykanye can i work on this?

**Comment by elroykanye** [comment]
Of course! Please go ahead :)

**Comment by elroykanye** [comment]
This has been marked as resolved
